:imagesdir: ../../assets/images
:page-time: 1
include::partial$style.adoc[]

[id="setup-lab5"]
== Setup the Lab working folder

[.indent2]
include::../_shared/close-tabs.adoc[]

. From your terminal in _Dev Spaces_, run the following command:
+
{blank}
+
[.copypaste]
****
step 9
****
+
{empty} +

. Check your lab folder
+
After executing the commands above, have a look in your editor's tree view to confirm it looks healthy. It should be similar to the folder structure you've seen in the previous exercise. 
+
--
[.indent2]
📁 workshop +
&nbsp;&nbsp;📁 lab +
&nbsp;&nbsp;&nbsp;&nbsp;📁 *data* pass:[<small style="color: #999">(mock inputs)</small>] +
&nbsp;&nbsp;&nbsp;&nbsp;📁 *prompt* pass:[<small style="color: #999">(model prompts)</small>] +
pass:[<mark style="padding-left: 1rem; background-color: white; color: purple"><b><i>&nbsp;!&nbsp;&nbsp;</i></b></mark>] *agent-main.camel.yaml* +
pass:[<mark style="padding-left: 1rem; background-color: white; color: purple"><b><i>&nbsp;!&nbsp;&nbsp;</i></b></mark>] *agent-tool-profile.camel.yaml* +
pass:[<mark style="padding-left: 1rem; background-color: white; color: grey"><b>&nbsp;⚙&nbsp;&nbsp;</b></mark>] *application.properties* +
pass:[<mark style="padding-left: 1rem; background-color: white; color: #b07219"><b>&nbsp;J&nbsp;&nbsp;</b></mark>] *PdfRenderer.java* +
pass:[<mark style="padding-left: 1rem; background-color: white; color: #b07219"><b>&nbsp;J&nbsp;&nbsp;</b></mark>] *s3Presigner.java* +
pass:[<mark style="padding-left: 1rem; background-color: white; color: grey"><b>&nbsp;≡&nbsp;&nbsp;</b></mark>] *template-pdf.xsl* +
--
+
{empty} +



[.verification]
****
Do you see the expected folder structure and files?

[.success]
You're ready to continue.

[.fail]
Make sure the syntax of the commands is compatible with your environment and try again.
****

{empty} +
