:imagesdir: ../../assets/images
:page-time: 1
include::partial$style.adoc[]

[id="setup-lab4"]
== Setup the Lab working folder

[.indent2]
include::../_shared/close-tabs.adoc[]

. From your terminal in _Dev Spaces_, run the following command:
+
{blank}
+
[.copypaste]
****
step 7
****
+
[TIP]
--
.Run the command above anytime to reset the exercise.
[%collapsible]
====
The workshop includes handy helper scripts that let you jump to any step or reset the lab to a known good state:

* `step N` — reset the lab to the beginning of step N
* `steps` — list all available steps in the lab
* `start` or `restart` — go to the very beginning (equivalent to `step 1`)
* `ff` — fast-forward to the *next* step
* `rw` — rewind to the *previous* step
====
--
+
{empty} +

. Check your lab folder
+
After executing the commands above, have a look in your editor's tree view to confirm it looks healthy. It should be similar to:
+
--
[.indent2]
📁 workshop +
&nbsp;&nbsp;📁 lab +
// &nbsp;&nbsp;&nbsp;&nbsp;📁 agent +
pass:[<mark style="padding-left: 1rem; background-color: white; color: purple"><b><i>&nbsp;!&nbsp;&nbsp;</i></b></mark>] *agent.camel.yaml* +
pass:[<mark style="padding-left: 1rem; background-color: white; color: grey"><b>&nbsp;⚙&nbsp;&nbsp;</b></mark>] *application.properties* +
pass:[<mark style="padding-left: 1rem; background-color: white; color: #b07219"><b>&nbsp;J&nbsp;&nbsp;</b></mark>] *PdfRenderer.java* +
pass:[<mark style="padding-left: 1rem; background-color: white; color: grey"><b>&nbsp;≡&nbsp;&nbsp;</b></mark>] *prompt.amend* +
pass:[<mark style="padding-left: 1rem; background-color: white; color: #b07219"><b>&nbsp;J&nbsp;&nbsp;</b></mark>] *s3Presigner.java* +
pass:[<mark style="padding-left: 1rem; background-color: white; color: grey"><b>&nbsp;≡&nbsp;&nbsp;</b></mark>] *system.message* +
pass:[<mark style="padding-left: 1rem; background-color: white; color: grey"><b>&nbsp;≡&nbsp;&nbsp;</b></mark>] *template-pdf.xsl* +

{empty} +

[.indent2]
NOTE: The `application.properties` file contains pre-configured settings for your environment — including AI model configuration and endpoint connectivity (database, S3 storage, and HelpDesk). It's ready to use, so you can focus on building the agentic flow.
--
+
{empty} +

[.verification]
****
Do you see the expected folder structure and files?

[.success]
You're ready to continue.

[.fail]
Try running `step 7` again and check that the files appear in your editor's file explorer.
****

{empty} +
